--------------------------------------------------------------------------------
-- OpsFlow 360
-- Patch: P02 - Core Relational Schema
-- Target: Oracle APEX SQL Workshop -> SQL Scripts
-- Creates: 17 tables, named constraints, supporting indexes, table comments
-- Safety: Fails before DDL when any non-recycle-bin OF_ object already exists.
-- Important: Oracle DDL commits. Follow the P02 recovery guide after any error.
--------------------------------------------------------------------------------

declare
  l_object_count number;
begin
  select count(*)
    into l_object_count
    from user_objects
   where object_name like 'OF\_%' escape '\'
     and object_name not like 'BIN$%';

  if l_object_count > 0 then
    raise_application_error(
      -20001,
      'P02 stopped: ' || l_object_count ||
      ' existing OF_ object(s) found. Do not mix installations.'
    );
  end if;

  dbms_output.put_line('P02 preflight passed: no existing OF_ objects.');
end;
/

--------------------------------------------------------------------------------
-- 01. Organization
--------------------------------------------------------------------------------

create table of_departments (
  id                number generated by default on null as identity,
  code              varchar2(30 char)                         not null,
  name              varchar2(200 char)                        not null,
  description       varchar2(1000 char),
  manager_user_id   number,
  is_active         char(1 char)             default 'Y'      not null,
  created_at        timestamp with local time zone
                                           default systimestamp not null,
  created_by        varchar2(255 char)       default 'SYSTEM'  not null,
  updated_at        timestamp with local time zone
                                           default systimestamp not null,
  updated_by        varchar2(255 char)       default 'SYSTEM'  not null,
  constraint of_departments_pk primary key (id),
  constraint of_departments_code_uk unique (code),
  constraint of_departments_code_ck
    check (code = upper(trim(code))),
  constraint of_departments_name_ck
    check (name = trim(name)),
  constraint of_departments_active_ck
    check (is_active in ('Y', 'N'))
);

comment on table of_departments is
  'Organization units used for membership, management scope, routing, and reporting.';

create table of_locations (
  id                number generated by default on null as identity,
  code              varchar2(30 char)                         not null,
  name              varchar2(200 char)                        not null,
  address_text      varchar2(1000 char),
  country_code      char(2 char),
  timezone_name     varchar2(100 char)                        not null,
  is_active         char(1 char)             default 'Y'      not null,
  created_at        timestamp with local time zone
                                           default systimestamp not null,
  created_by        varchar2(255 char)       default 'SYSTEM'  not null,
  updated_at        timestamp with local time zone
                                           default systimestamp not null,
  updated_by        varchar2(255 char)       default 'SYSTEM'  not null,
  constraint of_locations_pk primary key (id),
  constraint of_locations_code_uk unique (code),
  constraint of_locations_code_ck
    check (code = upper(trim(code))),
  constraint of_locations_name_ck
    check (name = trim(name)),
  constraint of_locations_country_ck
    check (country_code is null or country_code = upper(country_code)),
  constraint of_locations_active_ck
    check (is_active in ('Y', 'N'))
);

comment on table of_locations is
  'Physical or logical operating sites with named time-zone context.';

create table of_app_users (
  id                number generated by default on null as identity,
  username          varchar2(255 char)                        not null,
  email             varchar2(255 char)                        not null,
  display_name      varchar2(200 char)                        not null,
  department_id     number                                    not null,
  manager_user_id   number,
  location_id       number,
  locale_code       varchar2(20 char)        default 'en'     not null,
  timezone_name     varchar2(100 char)                        not null,
  is_active         char(1 char)             default 'Y'      not null,
  row_version       number                   default 1        not null,
  created_at        timestamp with local time zone
                                           default systimestamp not null,
  created_by        varchar2(255 char)       default 'SYSTEM'  not null,
  updated_at        timestamp with local time zone
                                           default systimestamp not null,
  updated_by        varchar2(255 char)       default 'SYSTEM'  not null,
  constraint of_app_users_pk primary key (id),
  constraint of_users_department_fk
    foreign key (department_id) references of_departments (id),
  constraint of_users_manager_fk
    foreign key (manager_user_id) references of_app_users (id),
  constraint of_users_location_fk
    foreign key (location_id) references of_locations (id),
  constraint of_users_username_ck
    check (username = trim(username)),
  constraint of_users_email_ck
    check (email = trim(email)),
  constraint of_users_display_name_ck
    check (display_name = trim(display_name)),
  constraint of_users_manager_self_ck
    check (manager_user_id is null or manager_user_id <> id),
  constraint of_users_locale_ck
    check (locale_code in ('en', 'ar')),
  constraint of_users_active_ck
    check (is_active in ('Y', 'N')),
  constraint of_users_row_version_ck
    check (row_version > 0)
);

comment on table of_app_users is
  'Business identities mapped from APEX authentication; no application password is stored.';

alter table of_departments add constraint of_departments_manager_fk
  foreign key (manager_user_id) references of_app_users (id);

create unique index of_users_username_uix
  on of_app_users (upper(trim(username)));

create unique index of_users_email_uix
  on of_app_users (upper(trim(email)));

create index of_departments_manager_ix
  on of_departments (manager_user_id);

create index of_users_department_ix
  on of_app_users (department_id);

create index of_users_manager_ix
  on of_app_users (manager_user_id);

create index of_users_location_ix
  on of_app_users (location_id);

--------------------------------------------------------------------------------
-- 02. Roles and settings
--------------------------------------------------------------------------------

create table of_roles (
  id                number generated by default on null as identity,
  code              varchar2(30 char)                         not null,
  name              varchar2(100 char)                        not null,
  description       varchar2(1000 char),
  is_active         char(1 char)             default 'Y'      not null,
  created_at        timestamp with local time zone
                                           default systimestamp not null,
  created_by        varchar2(255 char)       default 'SYSTEM'  not null,
  updated_at        timestamp with local time zone
                                           default systimestamp not null,
  updated_by        varchar2(255 char)       default 'SYSTEM'  not null,
  constraint of_roles_pk primary key (id),
  constraint of_roles_code_uk unique (code),
  constraint of_roles_code_ck
    check (code = upper(trim(code))),
  constraint of_roles_allowed_code_ck
    check (code in (
      'EMPLOYEE',
      'SERVICE_AGENT',
      'PROCUREMENT_OFFICER',
      'MANAGER',
      'OPERATIONS_ADMIN',
      'AUDITOR'
    )),
  constraint of_roles_name_ck
    check (name = trim(name)),
  constraint of_roles_active_ck
    check (is_active in ('Y', 'N'))
);

comment on table of_roles is
  'Stable application permission roles; users may hold multiple roles.';

create table of_user_roles (
  id                  number generated by default on null as identity,
  user_id             number                                    not null,
  role_id             number                                    not null,
  is_active           char(1 char)             default 'Y'      not null,
  granted_at          timestamp with local time zone
                                             default systimestamp not null,
  granted_by_user_id  number,
  revoked_at          timestamp with local time zone,
  revoked_by_user_id  number,
  created_at          timestamp with local time zone
                                             default systimestamp not null,
  created_by          varchar2(255 char)       default 'SYSTEM'  not null,
  updated_at          timestamp with local time zone
                                             default systimestamp not null,
  updated_by          varchar2(255 char)       default 'SYSTEM'  not null,
  constraint of_user_roles_pk primary key (id),
  constraint of_user_roles_uk unique (user_id, role_id),
  constraint of_user_roles_user_fk
    foreign key (user_id) references of_app_users (id),
  constraint of_user_roles_role_fk
    foreign key (role_id) references of_roles (id),
  constraint of_user_roles_granted_by_fk
    foreign key (granted_by_user_id) references of_app_users (id),
  constraint of_user_roles_revoked_by_fk
    foreign key (revoked_by_user_id) references of_app_users (id),
  constraint of_user_roles_active_ck
    check (is_active in ('Y', 'N')),
  constraint of_user_roles_revoke_ck
    check (
      (is_active = 'Y' and revoked_at is null and revoked_by_user_id is null)
      or
      (is_active = 'N' and revoked_at is not null)
    )
);

comment on table of_user_roles is
  'Current grant state for the many-to-many application user and role relationship.';

create index of_user_roles_role_ix
  on of_user_roles (role_id, is_active);

create index of_user_roles_granted_by_ix
  on of_user_roles (granted_by_user_id);

create index of_user_roles_revoked_by_ix
  on of_user_roles (revoked_by_user_id);

create table of_app_settings (
  id                number generated by default on null as identity,
  setting_code      varchar2(100 char)                        not null,
  data_type_code    varchar2(20 char)                         not null,
  setting_value     clob,
  description       varchar2(1000 char),
  is_sensitive      char(1 char)             default 'N'      not null,
  row_version       number                   default 1        not null,
  created_at        timestamp with local time zone
                                           default systimestamp not null,
  created_by        varchar2(255 char)       default 'SYSTEM'  not null,
  updated_at        timestamp with local time zone
                                           default systimestamp not null,
  updated_by        varchar2(255 char)       default 'SYSTEM'  not null,
  constraint of_app_settings_pk primary key (id),
  constraint of_app_settings_code_uk unique (setting_code),
  constraint of_settings_code_ck
    check (setting_code = upper(trim(setting_code))),
  constraint of_settings_type_ck
    check (data_type_code in ('TEXT', 'NUMBER', 'BOOLEAN', 'DATE', 'JSON')),
  constraint of_settings_sensitive_ck
    check (is_sensitive = 'N'),
  constraint of_settings_row_version_ck
    check (row_version > 0)
);

comment on table of_app_settings is
  'Non-secret business configuration. Credentials and tokens are explicitly excluded.';

--------------------------------------------------------------------------------
-- 03. Platform evidence and notifications
--------------------------------------------------------------------------------

create table of_audit_log (
  id                number generated by default on null as identity,
  occurred_at       timestamp with local time zone
                                           default systimestamp not null,
  actor_user_id     number,
  actor_name        varchar2(255 char)                        not null,
  action_code       varchar2(50 char)                         not null,
  entity_type_code  varchar2(50 char)                         not null,
  entity_id         number,
  entity_key        varchar2(100 char),
  old_values_json   clob,
  new_values_json   clob,
  correlation_id    varchar2(64 char)                         not null,
  app_id            number,
  page_id           number,
  constraint of_audit_log_pk primary key (id),
  constraint of_audit_actor_fk
    foreign key (actor_user_id) references of_app_users (id),
  constraint of_audit_action_ck
    check (action_code = upper(trim(action_code))),
  constraint of_audit_entity_type_ck
    check (entity_type_code = upper(trim(entity_type_code))),
  constraint of_audit_old_json_ck
    check (old_values_json is json),
  constraint of_audit_new_json_ck
    check (new_values_json is json)
);

comment on table of_audit_log is
  'Immutable sanitized before/after evidence for sensitive business changes.';

create index of_audit_actor_ix
  on of_audit_log (actor_user_id, occurred_at);

create index of_audit_entity_ix
  on of_audit_log (entity_type_code, entity_id, occurred_at);

create index of_audit_correlation_ix
  on of_audit_log (correlation_id);

create table of_error_log (
  id                number generated by default on null as identity,
  correlation_id    varchar2(64 char)                         not null,
  occurred_at       timestamp with local time zone
                                           default systimestamp not null,
  actor_user_id     number,
  location_code     varchar2(200 char)                        not null,
  error_message     varchar2(4000 char)                       not null,
  error_stack       clob,
  backtrace         clob,
  call_stack        clob,
  app_id            number,
  page_id           number,
  is_handled        char(1 char)             default 'N'      not null,
  constraint of_error_log_pk primary key (id),
  constraint of_error_correlation_uk unique (correlation_id),
  constraint of_error_actor_fk
    foreign key (actor_user_id) references of_app_users (id),
  constraint of_error_handled_ck
    check (is_handled in ('Y', 'N'))
);

comment on table of_error_log is
  'Server-side technical diagnostics identified to users by a safe correlation ID.';

create index of_error_actor_ix
  on of_error_log (actor_user_id, occurred_at);

create index of_error_occurred_ix
  on of_error_log (occurred_at);

create table of_notifications (
  id                      number generated by default on null as identity,
  recipient_user_id       number                                  not null,
  notification_type_code  varchar2(50 char)                       not null,
  title                   varchar2(200 char)                      not null,
  body_text               clob                                    not null,
  entity_type_code        varchar2(50 char),
  entity_id               number,
  channel_code            varchar2(20 char)                       not null,
  status_code             varchar2(20 char)      default 'PENDING' not null,
  idempotency_key         varchar2(200 char)                      not null,
  sent_at                 timestamp with local time zone,
  read_at                 timestamp with local time zone,
  attempt_count           number(5)              default 0        not null,
  last_error_text         varchar2(2000 char),
  created_at              timestamp with local time zone
                                                 default systimestamp not null,
  created_by              varchar2(255 char)     default 'SYSTEM'  not null,
  updated_at              timestamp with local time zone
                                                 default systimestamp not null,
  updated_by              varchar2(255 char)     default 'SYSTEM'  not null,
  constraint of_notifications_pk primary key (id),
  constraint of_notifications_idem_uk unique (idempotency_key),
  constraint of_notifications_recipient_fk
    foreign key (recipient_user_id) references of_app_users (id),
  constraint of_notifications_type_ck
    check (notification_type_code = upper(trim(notification_type_code))),
  constraint of_notifications_entity_ck
    check (entity_type_code is null or entity_type_code = upper(trim(entity_type_code))),
  constraint of_notifications_channel_ck
    check (channel_code in ('IN_APP', 'EMAIL')),
  constraint of_notifications_status_ck
    check (status_code in ('PENDING', 'SENT', 'FAILED', 'READ')),
  constraint of_notifications_attempt_ck
    check (attempt_count >= 0),
  constraint of_notifications_dates_ck
    check (
      (status_code = 'PENDING' and sent_at is null and read_at is null)
      or (status_code = 'FAILED' and read_at is null)
      or (status_code = 'SENT' and sent_at is not null and read_at is null)
      or (status_code = 'READ' and sent_at is not null and read_at is not null)
    )
);

comment on table of_notifications is
  'Retry-safe in-app and email notification records with unique idempotency keys.';

create index of_notifications_recipient_ix
  on of_notifications (recipient_user_id, status_code, created_at);

create index of_notifications_entity_ix
  on of_notifications (entity_type_code, entity_id);

--------------------------------------------------------------------------------
-- 04. Service catalogue and SLA
--------------------------------------------------------------------------------

create table of_priorities (
  id                number generated by default on null as identity,
  code              varchar2(30 char)                         not null,
  name              varchar2(100 char)                        not null,
  sort_order        number(4)                                 not null,
  severity_rank     number(2)                                 not null,
  is_active         char(1 char)             default 'Y'      not null,
  created_at        timestamp with local time zone
                                           default systimestamp not null,
  created_by        varchar2(255 char)       default 'SYSTEM'  not null,
  updated_at        timestamp with local time zone
                                           default systimestamp not null,
  updated_by        varchar2(255 char)       default 'SYSTEM'  not null,
  constraint of_priorities_pk primary key (id),
  constraint of_priorities_code_uk unique (code),
  constraint of_priorities_sort_uk unique (sort_order),
  constraint of_priorities_severity_uk unique (severity_rank),
  constraint of_priorities_code_ck
    check (code = upper(trim(code))),
  constraint of_priorities_name_ck
    check (name = trim(name)),
  constraint of_priorities_sort_ck
    check (sort_order > 0),
  constraint of_priorities_severity_ck
    check (severity_rank > 0),
  constraint of_priorities_active_ck
    check (is_active in ('Y', 'N'))
);

comment on table of_priorities is
  'Controlled urgency and impact levels used to select ticket SLA policies.';

create table of_service_categories (
  id                   number generated by default on null as identity,
  code                 varchar2(30 char)                         not null,
  name                 varchar2(200 char)                        not null,
  description          varchar2(2000 char),
  owner_department_id  number                                    not null,
  default_priority_id  number                                    not null,
  requires_location    char(1 char)             default 'N'      not null,
  is_active            char(1 char)             default 'Y'      not null,
  created_at           timestamp with local time zone
                                              default systimestamp not null,
  created_by           varchar2(255 char)       default 'SYSTEM'  not null,
  updated_at           timestamp with local time zone
                                              default systimestamp not null,
  updated_by           varchar2(255 char)       default 'SYSTEM'  not null,
  constraint of_service_categories_pk primary key (id),
  constraint of_service_categories_code_uk unique (code),
  constraint of_categories_owner_dept_fk
    foreign key (owner_department_id) references of_departments (id),
  constraint of_categories_default_priority_fk
    foreign key (default_priority_id) references of_priorities (id),
  constraint of_categories_code_ck
    check (code = upper(trim(code))),
  constraint of_categories_name_ck
    check (name = trim(name)),
  constraint of_categories_location_ck
    check (requires_location in ('Y', 'N')),
  constraint of_categories_active_ck
    check (is_active in ('Y', 'N'))
);

comment on table of_service_categories is
  'Employee-facing service catalogue entries owned by operational departments.';

create index of_categories_owner_dept_ix
  on of_service_categories (owner_department_id);

create index of_categories_priority_ix
  on of_service_categories (default_priority_id);

create table of_sla_policies (
  id                       number generated by default on null as identity,
  category_id              number                                  not null,
  priority_id              number                                  not null,
  response_minutes         number(9)                               not null,
  resolution_minutes       number(9)                               not null,
  warning_percent          number(5,2)            default 80       not null,
  pause_when_waiting_user  char(1 char)           default 'Y'      not null,
  effective_from           date                                    not null,
  effective_to             date,
  is_active                char(1 char)           default 'Y'      not null,
  row_version              number                 default 1        not null,
  created_at               timestamp with local time zone
                                                default systimestamp not null,
  created_by               varchar2(255 char)     default 'SYSTEM'  not null,
  updated_at               timestamp with local time zone
                                                default systimestamp not null,
  updated_by               varchar2(255 char)     default 'SYSTEM'  not null,
  constraint of_sla_policies_pk primary key (id),
  constraint of_sla_policies_effective_uk
    unique (category_id, priority_id, effective_from),
  constraint of_sla_policies_category_fk
    foreign key (category_id) references of_service_categories (id),
  constraint of_sla_policies_priority_fk
    foreign key (priority_id) references of_priorities (id),
  constraint of_sla_response_ck
    check (response_minutes > 0),
  constraint of_sla_resolution_ck
    check (resolution_minutes >= response_minutes),
  constraint of_sla_warning_ck
    check (warning_percent > 0 and warning_percent < 100),
  constraint of_sla_pause_ck
    check (pause_when_waiting_user in ('Y', 'N')),
  constraint of_sla_dates_ck
    check (effective_to is null or effective_to >= effective_from),
  constraint of_sla_active_ck
    check (is_active in ('Y', 'N')),
  constraint of_sla_row_version_ck
    check (row_version > 0)
);

comment on table of_sla_policies is
  'Effective-dated response and resolution targets by service category and priority.';

create index of_sla_policies_priority_ix
  on of_sla_policies (priority_id, is_active);

--------------------------------------------------------------------------------
-- 05. Ticket aggregate
--------------------------------------------------------------------------------

create table of_tickets (
  id                       number generated by default on null as identity,
  ticket_no                varchar2(30 char)                         not null,
  requester_user_id        number                                    not null,
  requester_department_id  number                                    not null,
  category_id              number                                    not null,
  priority_id              number                                    not null,
  sla_policy_id            number,
  location_id              number,
  assigned_agent_user_id   number,
  status_code              varchar2(30 char)        default 'DRAFT'  not null,
  source_code              varchar2(20 char)        default 'WEB'    not null,
  subject                  varchar2(200 char)                        not null,
  description              clob                                      not null,
  submitted_at             timestamp with local time zone,
  triaged_at               timestamp with local time zone,
  first_responded_at        timestamp with local time zone,
  response_due_at          timestamp with local time zone,
  resolution_due_at        timestamp with local time zone,
  waiting_started_at       timestamp with local time zone,
  resolved_at              timestamp with local time zone,
  closed_at                timestamp with local time zone,
  cancelled_at             timestamp with local time zone,
  resolution_summary       clob,
  closure_reason           varchar2(1000 char),
  row_version              number                   default 1        not null,
  created_at               timestamp with local time zone
                                                default systimestamp not null,
  created_by               varchar2(255 char)       default 'SYSTEM'  not null,
  updated_at               timestamp with local time zone
                                                default systimestamp not null,
  updated_by               varchar2(255 char)       default 'SYSTEM'  not null,
  constraint of_tickets_pk primary key (id),
  constraint of_tickets_no_uk unique (ticket_no),
  constraint of_tickets_requester_fk
    foreign key (requester_user_id) references of_app_users (id),
  constraint of_tickets_requester_dept_fk
    foreign key (requester_department_id) references of_departments (id),
  constraint of_tickets_category_fk
    foreign key (category_id) references of_service_categories (id),
  constraint of_tickets_priority_fk
    foreign key (priority_id) references of_priorities (id),
  constraint of_tickets_sla_policy_fk
    foreign key (sla_policy_id) references of_sla_policies (id),
  constraint of_tickets_location_fk
    foreign key (location_id) references of_locations (id),
  constraint of_tickets_agent_fk
    foreign key (assigned_agent_user_id) references of_app_users (id),
  constraint of_tickets_no_ck
    check (ticket_no = upper(trim(ticket_no))),
  constraint of_tickets_status_ck
    check (status_code in (
      'DRAFT', 'SUBMITTED', 'TRIAGED', 'IN_PROGRESS', 'WAITING_USER',
      'RESOLVED', 'CLOSED', 'REJECTED', 'CANCELLED'
    )),
  constraint of_tickets_source_ck
    check (source_code in ('WEB', 'REST')),
  constraint of_tickets_subject_ck
    check (subject = trim(subject)),
  constraint of_tickets_row_version_ck
    check (row_version > 0),
  constraint of_tickets_sla_required_ck
    check (
      status_code in ('DRAFT', 'CANCELLED')
      or (
        sla_policy_id is not null
        and response_due_at is not null
        and resolution_due_at is not null
      )
    ),
  constraint of_tickets_due_order_ck
    check (
      response_due_at is null
      or resolution_due_at is null
      or response_due_at <= resolution_due_at
    ),
  constraint of_tickets_assigned_ck
    check (
      status_code not in ('IN_PROGRESS', 'WAITING_USER', 'RESOLVED', 'CLOSED')
      or assigned_agent_user_id is not null
    ),
  constraint of_tickets_waiting_ck
    check (
      (status_code = 'WAITING_USER' and waiting_started_at is not null)
      or (status_code <> 'WAITING_USER' and waiting_started_at is null)
    ),
  constraint of_tickets_resolved_ck
    check (
      (status_code in ('RESOLVED', 'CLOSED') and resolved_at is not null)
      or (status_code not in ('RESOLVED', 'CLOSED') and resolved_at is null)
    ),
  constraint of_tickets_closed_ck
    check (
      (status_code = 'CLOSED' and closed_at is not null)
      or (status_code <> 'CLOSED' and closed_at is null)
    ),
  constraint of_tickets_cancelled_ck
    check (
      (status_code = 'CANCELLED' and cancelled_at is not null)
      or (status_code <> 'CANCELLED' and cancelled_at is null)
    )
);

comment on table of_tickets is
  'Current state and searchable facts for employee service requests.';

create index of_tickets_requester_status_ix
  on of_tickets (requester_user_id, status_code, created_at);

create index of_tickets_requester_dept_ix
  on of_tickets (requester_department_id, status_code);

create index of_tickets_agent_status_ix
  on of_tickets (assigned_agent_user_id, status_code, updated_at);

create index of_tickets_category_status_ix
  on of_tickets (category_id, priority_id, status_code);

create index of_tickets_sla_due_ix
  on of_tickets (status_code, resolution_due_at);

create index of_tickets_priority_ix
  on of_tickets (priority_id);

create index of_tickets_sla_policy_ix
  on of_tickets (sla_policy_id);

create index of_tickets_location_ix
  on of_tickets (location_id);

create table of_ticket_comments (
  id                   number generated by default on null as identity,
  ticket_id            number                                    not null,
  author_user_id       number,
  visibility_code      varchar2(20 char)        default 'PUBLIC'  not null,
  comment_text         clob                                      not null,
  is_system_generated  char(1 char)             default 'N'       not null,
  created_at           timestamp with local time zone
                                              default systimestamp not null,
  created_by           varchar2(255 char)       default 'SYSTEM'  not null,
  updated_at           timestamp with local time zone
                                              default systimestamp not null,
  updated_by           varchar2(255 char)       default 'SYSTEM'  not null,
  constraint of_ticket_comments_pk primary key (id),
  constraint of_comments_ticket_fk
    foreign key (ticket_id) references of_tickets (id),
  constraint of_comments_author_fk
    foreign key (author_user_id) references of_app_users (id),
  constraint of_comments_visibility_ck
    check (visibility_code in ('PUBLIC', 'INTERNAL')),
  constraint of_comments_system_ck
    check (is_system_generated in ('Y', 'N')),
  constraint of_comments_author_ck
    check (
      (is_system_generated = 'Y' and author_user_id is null)
      or (is_system_generated = 'N' and author_user_id is not null)
    )
);

comment on table of_ticket_comments is
  'Public ticket conversation and service-team internal notes.';

create index of_comments_ticket_time_ix
  on of_ticket_comments (ticket_id, created_at);

create index of_comments_author_ix
  on of_ticket_comments (author_user_id);

create table of_ticket_status_history (
  id                   number generated by default on null as identity,
  ticket_id            number                                    not null,
  from_status_code     varchar2(30 char),
  to_status_code       varchar2(30 char)                          not null,
  changed_at           timestamp with local time zone
                                              default systimestamp not null,
  changed_by_user_id   number,
  changed_by           varchar2(255 char)                         not null,
  reason_text          varchar2(1000 char),
  correlation_id       varchar2(64 char)                          not null,
  constraint of_ticket_status_history_pk primary key (id),
  constraint of_history_ticket_fk
    foreign key (ticket_id) references of_tickets (id),
  constraint of_history_changed_by_fk
    foreign key (changed_by_user_id) references of_app_users (id),
  constraint of_history_from_status_ck
    check (
      from_status_code is null
      or from_status_code in (
        'DRAFT', 'SUBMITTED', 'TRIAGED', 'IN_PROGRESS', 'WAITING_USER',
        'RESOLVED', 'CLOSED', 'REJECTED', 'CANCELLED'
      )
    ),
  constraint of_history_to_status_ck
    check (to_status_code in (
      'DRAFT', 'SUBMITTED', 'TRIAGED', 'IN_PROGRESS', 'WAITING_USER',
      'RESOLVED', 'CLOSED', 'REJECTED', 'CANCELLED'
    )),
  constraint of_history_transition_ck
    check (from_status_code is null or from_status_code <> to_status_code)
);

comment on table of_ticket_status_history is
  'Insert-only evidence of every ticket lifecycle transition.';

create index of_history_ticket_time_ix
  on of_ticket_status_history (ticket_id, changed_at);

create index of_history_changed_by_ix
  on of_ticket_status_history (changed_by_user_id);

create index of_history_correlation_ix
  on of_ticket_status_history (correlation_id);

create table of_ticket_sla_pauses (
  id                   number generated by default on null as identity,
  ticket_id            number                                    not null,
  started_at           timestamp with local time zone             not null,
  ended_at             timestamp with local time zone,
  duration_minutes     number(12),
  reason_code          varchar2(30 char)                          not null,
  started_by_user_id   number                                    not null,
  ended_by_user_id     number,
  constraint of_ticket_sla_pauses_pk primary key (id),
  constraint of_pauses_ticket_fk
    foreign key (ticket_id) references of_tickets (id),
  constraint of_pauses_started_by_fk
    foreign key (started_by_user_id) references of_app_users (id),
  constraint of_pauses_ended_by_fk
    foreign key (ended_by_user_id) references of_app_users (id),
  constraint of_pauses_reason_ck
    check (reason_code = 'WAITING_USER'),
  constraint of_pauses_dates_ck
    check (ended_at is null or ended_at >= started_at),
  constraint of_pauses_duration_ck
    check (
      (ended_at is null and duration_minutes is null and ended_by_user_id is null)
      or (
        ended_at is not null
        and duration_minutes is not null
        and duration_minutes >= 0
        and ended_by_user_id is not null
      )
    )
);

comment on table of_ticket_sla_pauses is
  'Recorded intervals that pause a ticket resolution clock while waiting for the requester.';

create unique index of_pauses_one_active_uix
  on of_ticket_sla_pauses (
    case when ended_at is null then ticket_id end
  );

create index of_pauses_ticket_started_ix
  on of_ticket_sla_pauses (ticket_id, started_at);

create index of_pauses_started_by_ix
  on of_ticket_sla_pauses (started_by_user_id);

create index of_pauses_ended_by_ix
  on of_ticket_sla_pauses (ended_by_user_id);

create table of_sla_events (
  id                 number generated by default on null as identity,
  ticket_id          number                                    not null,
  event_type_code    varchar2(30 char)                          not null,
  due_at_snapshot    timestamp with local time zone             not null,
  detected_at        timestamp with local time zone
                                            default systimestamp not null,
  notification_id    number,
  status_code        varchar2(20 char)        default 'DETECTED' not null,
  correlation_id     varchar2(64 char)                          not null,
  constraint of_sla_events_pk primary key (id),
  constraint of_sla_events_event_uk
    unique (ticket_id, event_type_code, due_at_snapshot),
  constraint of_sla_events_ticket_fk
    foreign key (ticket_id) references of_tickets (id),
  constraint of_sla_events_notification_fk
    foreign key (notification_id) references of_notifications (id),
  constraint of_sla_events_type_ck
    check (event_type_code in (
      'RESPONSE_WARNING', 'RESPONSE_BREACH',
      'RESOLUTION_WARNING', 'RESOLUTION_BREACH'
    )),
  constraint of_sla_events_status_ck
    check (status_code in ('DETECTED', 'NOTIFIED', 'FAILED'))
);

comment on table of_sla_events is
  'Retry-safe response and resolution warning/breach facts for ticket deadlines.';

create index of_sla_events_notification_ix
  on of_sla_events (notification_id);

create index of_sla_events_status_ix
  on of_sla_events (status_code, detected_at);

--------------------------------------------------------------------------------
-- 06. Completion summary
--------------------------------------------------------------------------------

select object_type,
       count(*) as object_count
  from user_objects
 where object_name like 'OF\_%' escape '\'
 group by object_type
 order by object_type;

select table_name,
       num_rows,
       last_analyzed
  from user_tables
 where table_name like 'OF\_%' escape '\'
 order by table_name;

--------------------------------------------------------------------------------
-- End P02 installer. Run P02_validate_core_schema.sql next.
--------------------------------------------------------------------------------
