--------------------------------------------------------------------------------
-- OpsFlow 360
-- Patch: P06 - Asset Lifecycle API
-- Target: Oracle APEX SQL Workshop -> SQL Scripts
-- Creates: 6 tables, reference seed, OF_ASSET_API, and history guard trigger
-- Safety: P05 must be valid and no P06 object may exist before installation.
-- Transaction: Reference seed commits; API actions use savepoints and never commit.
-- Important: Oracle DDL commits. Reject any run whose Summary has an error.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 00. Entry gate and physical asset schema
-- Dynamic DDL lets the prerequisite block fail before any P06 table is created.
--------------------------------------------------------------------------------

declare
  l_base_table_count number;
  l_p04_valid_count  number;
  l_p05_valid_count  number;
  l_demo_count       number;
  l_fixture_count    number;
  l_collision_count  number;

  procedure run_ddl(p_sql in varchar2) is
  begin
    execute immediate p_sql;
  end run_ddl;
begin
  select count(*)
    into l_base_table_count
    from user_tables
   where table_name in (
     'OF_LOCATIONS', 'OF_APP_USERS', 'OF_ROLES', 'OF_USER_ROLES',
     'OF_AUDIT_LOG'
   );

  select count(*)
    into l_p04_valid_count
    from user_objects
   where object_name in (
     'OF_UTIL_API', 'OF_SECURITY_API', 'OF_AUDIT_API', 'OF_ERROR_API',
     'OF_AUDIT_LOG_GUARD_TRG'
   )
     and object_type in ('PACKAGE', 'PACKAGE BODY', 'TRIGGER')
     and status = 'VALID';

  select count(*)
    into l_p05_valid_count
    from user_objects
   where object_name in ('OF_TICKET_API', 'OF_TICKET_HISTORY_GUARD_TRG')
     and object_type in ('PACKAGE', 'PACKAGE BODY', 'TRIGGER')
     and status = 'VALID';

  execute immediate
    'select count(*) from of_tickets where ticket_no like ''TKT-DEMO-%'''
    into l_demo_count;

  execute immediate q'~
    select
      (select count(*) from of_app_users
        where upper(username) in ('LAYLA.EMPLOYEE', 'YOUSSEF.EMPLOYEE')
          and is_active = 'Y')
      +
      (select count(*) from of_locations
        where code in ('CAI-HQ', 'ALX-OFFICE') and is_active = 'Y')
      from dual
  ~' into l_fixture_count;

  select count(*)
    into l_collision_count
    from user_objects
   where object_name in (
     'OF_ASSET_TYPES', 'OF_ASSETS', 'OF_ASSET_RESERVATIONS',
     'OF_ASSET_ASSIGNMENTS', 'OF_ASSET_REPAIRS',
     'OF_ASSET_STATUS_HISTORY', 'OF_ASSET_API',
     'OF_ASSET_HISTORY_GUARD_TRG'
   )
     and object_type in ('TABLE', 'PACKAGE', 'PACKAGE BODY', 'TRIGGER');

  if l_base_table_count <> 5 then
    raise_application_error(
      -20240,
      'P06 stopped: expected 5 required foundation tables, found ' ||
      l_base_table_count || '.'
    );
  end if;

  if l_p04_valid_count <> 9 or l_p05_valid_count <> 3 then
    raise_application_error(
      -20241,
      'P06 stopped: expected 9 valid P04 objects and 3 valid P05 objects; found ' ||
      l_p04_valid_count || ' and ' || l_p05_valid_count ||
      '. Complete P05 tests and final validation first.'
    );
  end if;

  if l_demo_count <> 12 or l_fixture_count <> 4 then
    raise_application_error(
      -20241,
      'P06 stopped: expected 12 P03 demo tickets and 4 required active ' ||
      'user/location fixtures; found ' || l_demo_count || ' and ' ||
      l_fixture_count || '. Restore and validate the P03 baseline first.'
    );
  end if;

  if l_collision_count <> 0 then
    raise_application_error(
      -20242,
      'P06 stopped: ' || l_collision_count ||
      ' P06 object(s) already exist. Validate the existing install or use the ' ||
      'guarded rollback; do not mix installations.'
    );
  end if;

  run_ddl(q'~
    create table of_asset_types (
      id                       number generated by default on null as identity,
      code                     varchar2(30 char)                         not null,
      name                     varchar2(200 char)                        not null,
      description              varchar2(1000 char),
      requires_serial_no       char(1 char)             default 'Y'      not null,
      default_warranty_months  number(4),
      is_active                char(1 char)             default 'Y'      not null,
      created_at               timestamp with local time zone
                                                       default systimestamp not null,
      created_by               varchar2(255 char)       default 'SYSTEM'  not null,
      updated_at               timestamp with local time zone
                                                       default systimestamp not null,
      updated_by               varchar2(255 char)       default 'SYSTEM'  not null,
      constraint of_asset_types_pk primary key (id),
      constraint of_asset_types_code_uk unique (code),
      constraint of_asset_types_code_ck check (code = upper(trim(code))),
      constraint of_asset_types_name_ck check (name = trim(name)),
      constraint of_asset_types_serial_ck check (requires_serial_no in ('Y', 'N')),
      constraint of_asset_types_warranty_ck
        check (default_warranty_months is null or default_warranty_months >= 0),
      constraint of_asset_types_active_ck check (is_active in ('Y', 'N'))
    )
  ~');

  run_ddl(q'~
    create table of_assets (
      id                       number generated by default on null as identity,
      asset_tag                varchar2(50 char)                         not null,
      asset_type_id            number                                    not null,
      serial_number            varchar2(100 char),
      asset_name               varchar2(200 char)                        not null,
      description              varchar2(2000 char),
      status_code              varchar2(30 char)        default 'IN_STOCK' not null,
      current_location_id      number                                    not null,
      acquisition_date         date,
      purchase_cost            number(14,2),
      currency_code            char(3 char),
      warranty_end_date        date,
      purchase_order_item_id   number,
      row_version              number                  default 1         not null,
      created_at               timestamp with local time zone
                                                       default systimestamp not null,
      created_by               varchar2(255 char)       default 'SYSTEM'  not null,
      updated_at               timestamp with local time zone
                                                       default systimestamp not null,
      updated_by               varchar2(255 char)       default 'SYSTEM'  not null,
      constraint of_assets_pk primary key (id),
      constraint of_assets_tag_uk unique (asset_tag),
      constraint of_assets_serial_uk unique (serial_number),
      constraint of_assets_type_fk
        foreign key (asset_type_id) references of_asset_types (id),
      constraint of_assets_location_fk
        foreign key (current_location_id) references of_locations (id),
      constraint of_assets_tag_ck check (asset_tag = upper(trim(asset_tag))),
      constraint of_assets_name_ck check (asset_name = trim(asset_name)),
      constraint of_assets_status_ck check (status_code in (
        'IN_STOCK', 'RESERVED', 'ASSIGNED', 'IN_REPAIR', 'RETIRED', 'LOST'
      )),
      constraint of_assets_cost_ck check (purchase_cost is null or purchase_cost >= 0),
      constraint of_assets_currency_ck check (
        (purchase_cost is null and currency_code is null)
        or
        (purchase_cost is not null and currency_code = upper(trim(currency_code)))
      ),
      constraint of_assets_warranty_ck check (
        warranty_end_date is null
        or acquisition_date is null
        or warranty_end_date >= acquisition_date
      ),
      constraint of_assets_row_version_ck check (row_version > 0)
    )
  ~');

  run_ddl(q'~
    create table of_asset_reservations (
      id                       number generated by default on null as identity,
      asset_id                 number                                    not null,
      reserved_for_user_id     number                                    not null,
      reserved_by_user_id      number                                    not null,
      reserved_at              timestamp with local time zone
                                                       default systimestamp not null,
      expires_at               timestamp with local time zone,
      released_at              timestamp with local time zone,
      released_by_user_id      number,
      status_code              varchar2(20 char)        default 'ACTIVE'  not null,
      reason_text              varchar2(1000 char),
      created_at               timestamp with local time zone
                                                       default systimestamp not null,
      created_by               varchar2(255 char)       default 'SYSTEM'  not null,
      updated_at               timestamp with local time zone
                                                       default systimestamp not null,
      updated_by               varchar2(255 char)       default 'SYSTEM'  not null,
      constraint of_asset_reservations_pk primary key (id),
      constraint of_asset_res_asset_fk
        foreign key (asset_id) references of_assets (id),
      constraint of_asset_res_for_user_fk
        foreign key (reserved_for_user_id) references of_app_users (id),
      constraint of_asset_res_by_user_fk
        foreign key (reserved_by_user_id) references of_app_users (id),
      constraint of_asset_res_release_user_fk
        foreign key (released_by_user_id) references of_app_users (id),
      constraint of_asset_res_status_ck check (
        status_code in ('ACTIVE', 'FULFILLED', 'RELEASED', 'EXPIRED')
      ),
      constraint of_asset_res_expiry_ck check (
        expires_at is null or expires_at > reserved_at
      ),
      constraint of_asset_res_interval_ck check (
        (status_code = 'ACTIVE' and released_at is null
          and released_by_user_id is null)
        or
        (status_code = 'FULFILLED' and released_at is not null
          and released_by_user_id is not null)
        or
        (status_code = 'RELEASED' and released_at is not null
          and released_by_user_id is not null and trim(reason_text) is not null)
        or
        (status_code = 'EXPIRED' and released_at is not null)
      )
    )
  ~');

  run_ddl(q'~
    create table of_asset_assignments (
      id                       number generated by default on null as identity,
      asset_id                 number                                    not null,
      assigned_to_user_id      number                                    not null,
      assigned_by_user_id      number                                    not null,
      assigned_at              timestamp with local time zone
                                                       default systimestamp not null,
      returned_at              timestamp with local time zone,
      returned_by_user_id      number,
      condition_out_code       varchar2(30 char)                          not null,
      condition_in_code        varchar2(30 char),
      notes                    varchar2(2000 char),
      created_at               timestamp with local time zone
                                                       default systimestamp not null,
      created_by               varchar2(255 char)       default 'SYSTEM'  not null,
      updated_at               timestamp with local time zone
                                                       default systimestamp not null,
      updated_by               varchar2(255 char)       default 'SYSTEM'  not null,
      constraint of_asset_assignments_pk primary key (id),
      constraint of_asset_asg_asset_fk
        foreign key (asset_id) references of_assets (id),
      constraint of_asset_asg_to_user_fk
        foreign key (assigned_to_user_id) references of_app_users (id),
      constraint of_asset_asg_by_user_fk
        foreign key (assigned_by_user_id) references of_app_users (id),
      constraint of_asset_asg_return_user_fk
        foreign key (returned_by_user_id) references of_app_users (id),
      constraint of_asset_asg_condition_out_ck check (
        condition_out_code in ('NEW', 'GOOD', 'FAIR', 'DAMAGED', 'LOST')
      ),
      constraint of_asset_asg_condition_in_ck check (
        condition_in_code is null
        or condition_in_code in ('NEW', 'GOOD', 'FAIR', 'DAMAGED', 'LOST')
      ),
      constraint of_asset_asg_interval_ck check (
        (returned_at is null and returned_by_user_id is null
          and condition_in_code is null)
        or
        (returned_at is not null and returned_by_user_id is not null
          and condition_in_code is not null and returned_at >= assigned_at)
      )
    )
  ~');

  run_ddl(q'~
    create table of_asset_repairs (
      id                       number generated by default on null as identity,
      asset_id                 number                                    not null,
      status_code              varchar2(20 char)        default 'OPEN'    not null,
      problem_description      clob                                      not null,
      resolution_description   clob,
      provider_name_snapshot   varchar2(200 char),
      supplier_id              number,
      opened_at                timestamp with local time zone
                                                       default systimestamp not null,
      closed_at                timestamp with local time zone,
      cost_amount              number(14,2),
      currency_code            char(3 char),
      row_version              number                  default 1         not null,
      created_at               timestamp with local time zone
                                                       default systimestamp not null,
      created_by               varchar2(255 char)       default 'SYSTEM'  not null,
      updated_at               timestamp with local time zone
                                                       default systimestamp not null,
      updated_by               varchar2(255 char)       default 'SYSTEM'  not null,
      constraint of_asset_repairs_pk primary key (id),
      constraint of_asset_rep_asset_fk
        foreign key (asset_id) references of_assets (id),
      constraint of_asset_rep_status_ck check (
        status_code in ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')
      ),
      constraint of_asset_rep_interval_ck check (
        (status_code in ('OPEN', 'IN_PROGRESS') and closed_at is null
          and resolution_description is null)
        or
        (status_code in ('COMPLETED', 'CANCELLED') and closed_at is not null
          and resolution_description is not null and closed_at >= opened_at)
      ),
      constraint of_asset_rep_cost_ck check (cost_amount is null or cost_amount >= 0),
      constraint of_asset_rep_currency_ck check (
        (cost_amount is null and currency_code is null)
        or
        (cost_amount is not null and currency_code = upper(trim(currency_code)))
      ),
      constraint of_asset_rep_row_version_ck check (row_version > 0)
    )
  ~');

  run_ddl(q'~
    create table of_asset_status_history (
      id                       number generated by default on null as identity,
      asset_id                 number                                    not null,
      from_status_code         varchar2(30 char),
      to_status_code           varchar2(30 char)                          not null,
      from_location_id         number,
      to_location_id           number,
      related_user_id          number,
      changed_at               timestamp with local time zone
                                                       default systimestamp not null,
      changed_by_user_id       number                                    not null,
      reason_text              varchar2(1000 char),
      correlation_id           varchar2(64 char)                          not null,
      constraint of_asset_status_history_pk primary key (id),
      constraint of_asset_hist_asset_fk
        foreign key (asset_id) references of_assets (id),
      constraint of_asset_hist_from_loc_fk
        foreign key (from_location_id) references of_locations (id),
      constraint of_asset_hist_to_loc_fk
        foreign key (to_location_id) references of_locations (id),
      constraint of_asset_hist_related_user_fk
        foreign key (related_user_id) references of_app_users (id),
      constraint of_asset_hist_changed_user_fk
        foreign key (changed_by_user_id) references of_app_users (id),
      constraint of_asset_hist_from_status_ck check (
        from_status_code is null or from_status_code in (
          'IN_STOCK', 'RESERVED', 'ASSIGNED', 'IN_REPAIR', 'RETIRED', 'LOST'
        )
      ),
      constraint of_asset_hist_to_status_ck check (to_status_code in (
        'IN_STOCK', 'RESERVED', 'ASSIGNED', 'IN_REPAIR', 'RETIRED', 'LOST'
      ))
    )
  ~');

  run_ddl('create index of_assets_type_ix on of_assets (asset_type_id)');
  run_ddl('create index of_assets_location_ix on of_assets (current_location_id)');
  run_ddl('create index of_asset_res_asset_ix on of_asset_reservations (asset_id)');
  run_ddl('create index of_asset_res_for_user_ix on of_asset_reservations (reserved_for_user_id, status_code)');
  run_ddl(q'~create unique index of_asset_res_active_uix on of_asset_reservations (
    case when status_code = 'ACTIVE' then asset_id end
  )~');
  run_ddl('create index of_asset_asg_asset_ix on of_asset_assignments (asset_id)');
  run_ddl('create index of_asset_asg_user_ix on of_asset_assignments (assigned_to_user_id, returned_at)');
  run_ddl(q'~create unique index of_asset_asg_active_uix on of_asset_assignments (
    case when returned_at is null then asset_id end
  )~');
  run_ddl('create index of_asset_rep_asset_ix on of_asset_repairs (asset_id)');
  run_ddl(q'~create unique index of_asset_rep_active_uix on of_asset_repairs (
    case when status_code in ('OPEN', 'IN_PROGRESS') then asset_id end
  )~');
  run_ddl('create index of_asset_hist_asset_ix on of_asset_status_history (asset_id, changed_at)');
  run_ddl('create index of_asset_hist_correlation_ix on of_asset_status_history (correlation_id)');

  run_ddl(q'~comment on table of_asset_types is
    'Asset classifications and default serial/warranty policy.'~');
  run_ddl(q'~comment on table of_assets is
    'Current state of individually tracked company assets.'~');
  run_ddl(q'~comment on table of_asset_reservations is
    'Auditable reservation intervals; at most one ACTIVE row per asset.'~');
  run_ddl(q'~comment on table of_asset_assignments is
    'Custody intervals; at most one unreturned assignment per asset.'~');
  run_ddl(q'~comment on table of_asset_repairs is
    'Repair cases; at most one OPEN or IN_PROGRESS case per asset.'~');
  run_ddl(q'~comment on table of_asset_status_history is
    'Immutable asset status, location, and related-user transition evidence.'~');

  dbms_output.put_line('P06 prerequisite check and physical schema creation passed.');
end;
/

--------------------------------------------------------------------------------
-- 01. Seed six reusable asset types
--------------------------------------------------------------------------------

declare
  l_seed_count number;
begin
  merge into of_asset_types t
  using (
    select 'LAPTOP' code, 'Laptop' name,
           'Portable employee computer.' description,
           'Y' requires_serial_no, 36 warranty_months from dual
    union all select 'DESKTOP', 'Desktop',
           'Fixed workstation computer.', 'Y', 36 from dual
    union all select 'MONITOR', 'Monitor',
           'External display device.', 'Y', 36 from dual
    union all select 'MOBILE_PHONE', 'Mobile Phone',
           'Company-managed mobile telephone.', 'Y', 24 from dual
    union all select 'PRINTER', 'Printer',
           'Managed printing device.', 'Y', 24 from dual
    union all select 'FURNITURE', 'Furniture',
           'Individually tracked office furniture.', 'N', 60 from dual
  ) s
  on (t.code = s.code)
  when matched then update set
    t.name = s.name,
    t.description = s.description,
    t.requires_serial_no = s.requires_serial_no,
    t.default_warranty_months = s.warranty_months,
    t.is_active = 'Y',
    t.updated_at = systimestamp,
    t.updated_by = 'P06_SEED'
  when not matched then insert (
    code, name, description, requires_serial_no,
    default_warranty_months, is_active, created_by, updated_by
  ) values (
    s.code, s.name, s.description, s.requires_serial_no,
    s.warranty_months, 'Y', 'P06_SEED', 'P06_SEED'
  );

  select count(*)
    into l_seed_count
    from of_asset_types
   where code in (
     'LAPTOP', 'DESKTOP', 'MONITOR', 'MOBILE_PHONE', 'PRINTER', 'FURNITURE'
   )
     and is_active = 'Y';

  if l_seed_count <> 6 then
    rollback;
    raise_application_error(
      -20242,
      'P06 seed stopped: expected 6 active asset types, found ' ||
      l_seed_count || '.'
    );
  end if;

  commit;
  dbms_output.put_line('P06 reference seed committed: 6 active asset types.');
end;
/

--------------------------------------------------------------------------------
-- 02. Public asset transaction contract
--------------------------------------------------------------------------------

create or replace package of_asset_api authid definer as
  procedure register_asset(
    p_asset_tag              in  varchar2,
    p_asset_type_id          in  number,
    p_serial_number          in  varchar2 default null,
    p_asset_name             in  varchar2,
    p_description            in  varchar2 default null,
    p_location_id            in  number,
    p_acquisition_date       in  date default null,
    p_purchase_cost          in  number default null,
    p_currency_code          in  varchar2 default null,
    p_warranty_end_date      in  date default null,
    p_asset_id               out number,
    p_row_version            out number
  );

  procedure reserve_asset(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_reserved_for_user_id   in  number,
    p_expires_at             in  timestamp with local time zone default null,
    p_reason_text            in  varchar2 default null,
    p_reservation_id         out number,
    p_new_row_version        out number
  );

  procedure release_reservation(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_reason_text            in  varchar2,
    p_new_row_version        out number
  );

  procedure assign_asset(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_assigned_to_user_id    in  number,
    p_condition_out_code     in  varchar2,
    p_to_location_id         in  number default null,
    p_notes                  in  varchar2 default null,
    p_assignment_id          out number,
    p_new_row_version        out number
  );

  procedure transfer_asset(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_new_custodian_user_id  in  number,
    p_condition_in_code      in  varchar2,
    p_condition_out_code     in  varchar2,
    p_to_location_id         in  number default null,
    p_reason_text            in  varchar2,
    p_new_assignment_id      out number,
    p_new_row_version        out number
  );

  procedure return_asset(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_return_location_id     in  number,
    p_condition_in_code      in  varchar2,
    p_notes                  in  varchar2 default null,
    p_new_row_version        out number
  );

  procedure open_repair(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_problem_description    in  clob,
    p_provider_name          in  varchar2 default null,
    p_repair_location_id     in  number default null,
    p_condition_in_code      in  varchar2 default null,
    p_repair_id              out number,
    p_new_row_version        out number
  );

  procedure complete_repair_to_stock(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_repair_id              in  number,
    p_resolution_description in  clob,
    p_stock_location_id      in  number,
    p_cost_amount            in  number default null,
    p_currency_code          in  varchar2 default null,
    p_new_row_version        out number
  );

  procedure complete_repair_to_custodian(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_repair_id              in  number,
    p_resolution_description in  clob,
    p_custodian_user_id      in  number,
    p_condition_out_code     in  varchar2,
    p_to_location_id         in  number,
    p_cost_amount            in  number default null,
    p_currency_code          in  varchar2 default null,
    p_assignment_id          out number,
    p_new_row_version        out number
  );

  procedure mark_lost(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_reason_text            in  varchar2,
    p_new_row_version        out number
  );

  procedure retire_asset(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_reason_text            in  varchar2,
    p_new_row_version        out number
  );
end of_asset_api;
/

--------------------------------------------------------------------------------
-- 03. Asset lifecycle implementation
--------------------------------------------------------------------------------

create or replace package body of_asset_api as
  procedure fail(p_code in number, p_message in varchar2) is
  begin
    raise_application_error(p_code, p_message);
  end fail;

  procedure assert_text(
    p_value      in varchar2,
    p_label      in varchar2,
    p_max_length in number
  ) is
  begin
    if trim(p_value) is null then
      fail(-20200, p_label || ' is required.');
    end if;
    if length(trim(p_value)) > p_max_length then
      fail(-20200, p_label || ' exceeds ' || p_max_length || ' characters.');
    end if;
  end assert_text;

  procedure assert_clob_text(p_value in clob, p_label in varchar2) is
    l_probe varchar2(4000 char);
  begin
    if p_value is null then
      fail(-20200, p_label || ' is required.');
    end if;
    l_probe := dbms_lob.substr(p_value, 4000, 1);
    if trim(l_probe) is null then
      fail(-20200, p_label || ' must contain nonblank text.');
    end if;
  end assert_clob_text;

  procedure assert_admin is
  begin
    of_security_api.assert_authenticated;
    if not of_security_api.is_operations_admin() then
      fail(-20205, 'An operations administrator role is required.');
    end if;
  end assert_admin;

  procedure assert_user(p_user_id in number) is
    l_count number;
  begin
    select count(*) into l_count
      from of_app_users
     where id = p_user_id and is_active = 'Y';
    if l_count <> 1 then
      fail(-20206, 'The selected user is missing or inactive.');
    end if;
  end assert_user;

  procedure assert_location(p_location_id in number) is
    l_count number;
  begin
    if p_location_id is null then
      fail(-20206, 'An active location is required.');
    end if;
    select count(*) into l_count
      from of_locations
     where id = p_location_id and is_active = 'Y';
    if l_count <> 1 then
      fail(-20206, 'The selected location is missing or inactive.');
    end if;
  end assert_location;

  function normalized_condition(p_value in varchar2) return varchar2 is
    l_value varchar2(30 char);
  begin
    l_value := of_util_api.normalize_code(p_value);
    if l_value is null
       or l_value not in ('NEW', 'GOOD', 'FAIR', 'DAMAGED', 'LOST') then
      fail(-20200, 'Condition must be NEW, GOOD, FAIR, DAMAGED, or LOST.');
    end if;
    return l_value;
  end normalized_condition;

  procedure validate_money(
    p_amount        in  number,
    p_currency_code in  varchar2,
    p_normalized    out varchar2
  ) is
  begin
    p_normalized := of_util_api.normalize_code(p_currency_code);
    if p_amount is null and p_normalized is not null then
      fail(-20200, 'Currency cannot be supplied without an amount.');
    elsif p_amount is not null then
      if p_amount < 0 then
        fail(-20200, 'Amount cannot be negative.');
      end if;
      if p_normalized is null
         or not regexp_like(p_normalized, '^[A-Z]{3}$') then
        fail(-20200, 'A three-letter uppercase currency code is required.');
      end if;
    end if;
  end validate_money;

  procedure assert_consistent(p_asset in of_assets%rowtype) is
    l_reservations number;
    l_assignments  number;
    l_repairs      number;
    l_valid        boolean := false;
  begin
    select count(*) into l_reservations
      from of_asset_reservations
     where asset_id = p_asset.id and status_code = 'ACTIVE';
    select count(*) into l_assignments
      from of_asset_assignments
     where asset_id = p_asset.id and returned_at is null;
    select count(*) into l_repairs
      from of_asset_repairs
     where asset_id = p_asset.id and status_code in ('OPEN', 'IN_PROGRESS');

    case p_asset.status_code
      when 'IN_STOCK' then
        l_valid := l_reservations = 0 and l_assignments = 0 and l_repairs = 0;
      when 'RESERVED' then
        l_valid := l_reservations = 1 and l_assignments = 0 and l_repairs = 0;
      when 'ASSIGNED' then
        l_valid := l_reservations = 0 and l_assignments = 1 and l_repairs = 0;
      when 'IN_REPAIR' then
        l_valid := l_reservations = 0 and l_assignments = 0 and l_repairs = 1;
      when 'RETIRED' then
        l_valid := l_reservations = 0 and l_assignments = 0 and l_repairs = 0;
      when 'LOST' then
        l_valid := l_reservations = 0 and l_assignments = 0 and l_repairs = 0;
      else
        l_valid := false;
    end case;

    if not l_valid then
      fail(
        -20208,
        'Asset status disagrees with its active reservation, custody, or repair row.'
      );
    end if;
  end assert_consistent;

  procedure lock_asset(
    p_asset_id             in  number,
    p_expected_row_version in  number,
    p_asset                out of_assets%rowtype
  ) is
    e_resource_busy exception;
    pragma exception_init(e_resource_busy, -54);
  begin
    assert_admin;
    if p_asset_id is null or p_expected_row_version is null
       or p_expected_row_version < 1 then
      fail(-20200, 'Asset ID and expected row version are required.');
    end if;

    select * into p_asset
      from of_assets
     where id = p_asset_id
       for update nowait;

    if p_asset.row_version <> p_expected_row_version then
      fail(-20202, 'Asset changed since it was loaded. Refresh and try again.');
    end if;
    assert_consistent(p_asset);
  exception
    when no_data_found then
      fail(-20201, 'Asset does not exist or is no longer available.');
    when e_resource_busy then
      fail(-20203, 'Asset is currently being changed by another session.');
  end lock_asset;

  function state_json(
    p_status_code in varchar2,
    p_row_version in number,
    p_location_id in number,
    p_related_user_id in number
  ) return clob is
    l_json json_object_t := json_object_t();
  begin
    if p_status_code is null then l_json.put_null('statusCode');
    else l_json.put('statusCode', p_status_code); end if;
    if p_row_version is null then l_json.put_null('rowVersion');
    else l_json.put('rowVersion', p_row_version); end if;
    if p_location_id is null then l_json.put_null('locationId');
    else l_json.put('locationId', p_location_id); end if;
    if p_related_user_id is null then l_json.put_null('relatedUserId');
    else l_json.put('relatedUserId', p_related_user_id); end if;
    return l_json.to_clob();
  end state_json;

  procedure record_event(
    p_action_code         in varchar2,
    p_asset_id           in number,
    p_asset_tag          in varchar2,
    p_from_status        in varchar2,
    p_to_status          in varchar2,
    p_from_location_id   in number,
    p_to_location_id     in number,
    p_old_related_user_id in number,
    p_new_related_user_id in number,
    p_reason_text        in varchar2,
    p_old_version        in number,
    p_new_version        in number
  ) is
    l_actor_id       number;
    l_correlation_id varchar2(64 char);
    l_recorded_id     varchar2(64 char);
  begin
    l_actor_id := of_security_api.current_user_id();
    l_correlation_id := of_util_api.new_correlation_id();

    insert into of_asset_status_history (
      asset_id, from_status_code, to_status_code,
      from_location_id, to_location_id, related_user_id,
      changed_at, changed_by_user_id, reason_text, correlation_id
    ) values (
      p_asset_id, p_from_status, p_to_status,
      p_from_location_id, p_to_location_id,
      coalesce(p_new_related_user_id, p_old_related_user_id),
      systimestamp, l_actor_id, substr(trim(p_reason_text), 1, 1000),
      l_correlation_id
    );

    l_recorded_id := of_audit_api.record_event(
      p_action_code      => p_action_code,
      p_entity_type_code => 'ASSET',
      p_entity_id        => p_asset_id,
      p_entity_key       => p_asset_tag,
      p_old_values_json  => state_json(
        p_from_status, p_old_version, p_from_location_id,
        p_old_related_user_id
      ),
      p_new_values_json  => state_json(
        p_to_status, p_new_version, p_to_location_id,
        p_new_related_user_id
      ),
      p_correlation_id   => l_correlation_id
    );
  end record_event;

  procedure register_asset(
    p_asset_tag              in  varchar2,
    p_asset_type_id          in  number,
    p_serial_number          in  varchar2 default null,
    p_asset_name             in  varchar2,
    p_description            in  varchar2 default null,
    p_location_id            in  number,
    p_acquisition_date       in  date default null,
    p_purchase_cost          in  number default null,
    p_currency_code          in  varchar2 default null,
    p_warranty_end_date      in  date default null,
    p_asset_id               out number,
    p_row_version            out number
  ) is
    l_actor_name       varchar2(255 char);
    l_asset_tag        varchar2(50 char);
    l_serial_number    varchar2(100 char);
    l_requires_serial  char(1 char);
    l_warranty_months  number;
    l_warranty_end     date;
    l_currency_code    varchar2(3 char);
  begin
    savepoint of_asset_api_action;
    p_asset_id := null;
    p_row_version := null;

    assert_admin;
    assert_text(p_asset_tag, 'Asset tag', 50);
    assert_text(p_asset_name, 'Asset name', 200);
    assert_location(p_location_id);
    validate_money(p_purchase_cost, p_currency_code, l_currency_code);

    l_actor_name := of_security_api.current_username();
    l_asset_tag := of_util_api.normalize_code(p_asset_tag);
    l_serial_number := upper(trim(p_serial_number));

    begin
      select requires_serial_no, default_warranty_months
        into l_requires_serial, l_warranty_months
        from of_asset_types
       where id = p_asset_type_id and is_active = 'Y';
    exception
      when no_data_found then
        fail(-20206, 'The selected asset type is missing or inactive.');
    end;

    if l_requires_serial = 'Y' and l_serial_number is null then
      fail(-20207, 'A serial number is required for this asset type.');
    end if;
    if l_serial_number is not null and length(l_serial_number) > 100 then
      fail(-20200, 'Serial number exceeds 100 characters.');
    end if;
    if p_warranty_end_date is not null and p_acquisition_date is not null
       and p_warranty_end_date < p_acquisition_date then
      fail(-20200, 'Warranty end date cannot precede acquisition date.');
    end if;

    l_warranty_end := p_warranty_end_date;
    if l_warranty_end is null and p_acquisition_date is not null
       and l_warranty_months is not null then
      l_warranty_end := add_months(p_acquisition_date, l_warranty_months);
    end if;

    insert into of_assets (
      asset_tag, asset_type_id, serial_number, asset_name, description,
      status_code, current_location_id, acquisition_date, purchase_cost,
      currency_code, warranty_end_date, row_version, created_by, updated_by
    ) values (
      l_asset_tag, p_asset_type_id, l_serial_number, trim(p_asset_name),
      substr(trim(p_description), 1, 2000), 'IN_STOCK', p_location_id,
      p_acquisition_date, p_purchase_cost, l_currency_code, l_warranty_end,
      1, l_actor_name, l_actor_name
    ) returning id, row_version into p_asset_id, p_row_version;

    record_event(
      'ASSET_REGISTERED', p_asset_id, l_asset_tag,
      null, 'IN_STOCK', null, p_location_id,
      null, null, 'Asset registered', null, p_row_version
    );
  exception
    when others then
      rollback to of_asset_api_action;
      raise;
  end register_asset;

  procedure reserve_asset(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_reserved_for_user_id   in  number,
    p_expires_at             in  timestamp with local time zone default null,
    p_reason_text            in  varchar2 default null,
    p_reservation_id         out number,
    p_new_row_version        out number
  ) is
    l_asset      of_assets%rowtype;
    l_actor_id   number;
    l_actor_name varchar2(255 char);
  begin
    savepoint of_asset_api_action;
    p_reservation_id := null;
    p_new_row_version := null;
    lock_asset(p_asset_id, p_expected_row_version, l_asset);
    if l_asset.status_code <> 'IN_STOCK' then
      fail(-20204, 'Reserve is allowed only while an asset is IN_STOCK.');
    end if;
    assert_user(p_reserved_for_user_id);
    if p_expires_at is not null and p_expires_at <= systimestamp then
      fail(-20200, 'Reservation expiry must be in the future.');
    end if;

    l_actor_id := of_security_api.current_user_id();
    l_actor_name := of_security_api.current_username();
    insert into of_asset_reservations (
      asset_id, reserved_for_user_id, reserved_by_user_id,
      reserved_at, expires_at, status_code, reason_text,
      created_by, updated_by
    ) values (
      l_asset.id, p_reserved_for_user_id, l_actor_id,
      systimestamp, p_expires_at, 'ACTIVE',
      substr(trim(p_reason_text), 1, 1000), l_actor_name, l_actor_name
    ) returning id into p_reservation_id;

    update of_assets
       set status_code = 'RESERVED', row_version = row_version + 1,
           updated_at = systimestamp, updated_by = l_actor_name
     where id = l_asset.id
     returning row_version into p_new_row_version;

    record_event(
      'ASSET_RESERVED', l_asset.id, l_asset.asset_tag,
      'IN_STOCK', 'RESERVED', l_asset.current_location_id,
      l_asset.current_location_id, null, p_reserved_for_user_id,
      p_reason_text, l_asset.row_version, p_new_row_version
    );
  exception
    when others then rollback to of_asset_api_action; raise;
  end reserve_asset;

  procedure release_reservation(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_reason_text            in  varchar2,
    p_new_row_version        out number
  ) is
    l_asset         of_assets%rowtype;
    l_reservation_id number;
    l_reserved_for  number;
    l_actor_id      number;
    l_actor_name    varchar2(255 char);
  begin
    savepoint of_asset_api_action;
    p_new_row_version := null;
    assert_text(p_reason_text, 'Release reason', 1000);
    lock_asset(p_asset_id, p_expected_row_version, l_asset);
    if l_asset.status_code <> 'RESERVED' then
      fail(-20204, 'Release is allowed only while an asset is RESERVED.');
    end if;

    select id, reserved_for_user_id
      into l_reservation_id, l_reserved_for
      from of_asset_reservations
     where asset_id = l_asset.id and status_code = 'ACTIVE'
       for update;

    l_actor_id := of_security_api.current_user_id();
    l_actor_name := of_security_api.current_username();
    update of_asset_reservations
       set status_code = 'RELEASED', released_at = systimestamp,
           released_by_user_id = l_actor_id,
           reason_text = substr(trim(p_reason_text), 1, 1000),
           updated_at = systimestamp, updated_by = l_actor_name
     where id = l_reservation_id;

    update of_assets
       set status_code = 'IN_STOCK', row_version = row_version + 1,
           updated_at = systimestamp, updated_by = l_actor_name
     where id = l_asset.id
     returning row_version into p_new_row_version;

    record_event(
      'RESERVATION_RELEASED', l_asset.id, l_asset.asset_tag,
      'RESERVED', 'IN_STOCK', l_asset.current_location_id,
      l_asset.current_location_id, l_reserved_for, null,
      p_reason_text, l_asset.row_version, p_new_row_version
    );
  exception
    when no_data_found then
      rollback to of_asset_api_action;
      fail(-20208, 'The active reservation is missing.');
    when others then rollback to of_asset_api_action; raise;
  end release_reservation;

  procedure assign_asset(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_assigned_to_user_id    in  number,
    p_condition_out_code     in  varchar2,
    p_to_location_id         in  number default null,
    p_notes                  in  varchar2 default null,
    p_assignment_id          out number,
    p_new_row_version        out number
  ) is
    l_asset          of_assets%rowtype;
    l_condition      varchar2(30 char);
    l_location_id    number;
    l_actor_id       number;
    l_actor_name     varchar2(255 char);
    l_reservation_id number;
    l_reserved_for   number;
  begin
    savepoint of_asset_api_action;
    p_assignment_id := null;
    p_new_row_version := null;
    lock_asset(p_asset_id, p_expected_row_version, l_asset);
    if l_asset.status_code not in ('IN_STOCK', 'RESERVED') then
      fail(-20204, 'Assign is allowed only from IN_STOCK or RESERVED.');
    end if;
    assert_user(p_assigned_to_user_id);
    l_condition := normalized_condition(p_condition_out_code);
    l_location_id := coalesce(p_to_location_id, l_asset.current_location_id);
    assert_location(l_location_id);
    l_actor_id := of_security_api.current_user_id();
    l_actor_name := of_security_api.current_username();

    if l_asset.status_code = 'RESERVED' then
      select id, reserved_for_user_id
        into l_reservation_id, l_reserved_for
        from of_asset_reservations
       where asset_id = l_asset.id and status_code = 'ACTIVE'
         for update;
      if l_reserved_for <> p_assigned_to_user_id then
        fail(-20204, 'The reservation belongs to a different intended custodian.');
      end if;
      update of_asset_reservations
         set status_code = 'FULFILLED', released_at = systimestamp,
             released_by_user_id = l_actor_id,
             updated_at = systimestamp, updated_by = l_actor_name
       where id = l_reservation_id;
    end if;

    insert into of_asset_assignments (
      asset_id, assigned_to_user_id, assigned_by_user_id, assigned_at,
      condition_out_code, notes, created_by, updated_by
    ) values (
      l_asset.id, p_assigned_to_user_id, l_actor_id, systimestamp,
      l_condition, substr(trim(p_notes), 1, 2000), l_actor_name, l_actor_name
    ) returning id into p_assignment_id;

    update of_assets
       set status_code = 'ASSIGNED', current_location_id = l_location_id,
           row_version = row_version + 1,
           updated_at = systimestamp, updated_by = l_actor_name
     where id = l_asset.id
     returning row_version into p_new_row_version;

    record_event(
      'ASSET_ASSIGNED', l_asset.id, l_asset.asset_tag,
      l_asset.status_code, 'ASSIGNED', l_asset.current_location_id,
      l_location_id,
      case when l_asset.status_code = 'RESERVED' then l_reserved_for end,
      p_assigned_to_user_id, p_notes,
      l_asset.row_version, p_new_row_version
    );
  exception
    when no_data_found then
      rollback to of_asset_api_action;
      fail(-20208, 'The active reservation is missing.');
    when others then rollback to of_asset_api_action; raise;
  end assign_asset;

  procedure transfer_asset(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_new_custodian_user_id  in  number,
    p_condition_in_code      in  varchar2,
    p_condition_out_code     in  varchar2,
    p_to_location_id         in  number default null,
    p_reason_text            in  varchar2,
    p_new_assignment_id      out number,
    p_new_row_version        out number
  ) is
    l_asset            of_assets%rowtype;
    l_old_assignment_id number;
    l_old_custodian    number;
    l_condition_in     varchar2(30 char);
    l_condition_out    varchar2(30 char);
    l_location_id      number;
    l_actor_id         number;
    l_actor_name       varchar2(255 char);
  begin
    savepoint of_asset_api_action;
    p_new_assignment_id := null;
    p_new_row_version := null;
    assert_text(p_reason_text, 'Transfer reason', 1000);
    lock_asset(p_asset_id, p_expected_row_version, l_asset);
    if l_asset.status_code <> 'ASSIGNED' then
      fail(-20204, 'Transfer is allowed only while an asset is ASSIGNED.');
    end if;
    assert_user(p_new_custodian_user_id);
    l_condition_in := normalized_condition(p_condition_in_code);
    l_condition_out := normalized_condition(p_condition_out_code);
    l_location_id := coalesce(p_to_location_id, l_asset.current_location_id);
    assert_location(l_location_id);

    select id, assigned_to_user_id
      into l_old_assignment_id, l_old_custodian
      from of_asset_assignments
     where asset_id = l_asset.id and returned_at is null
       for update;
    if l_old_custodian = p_new_custodian_user_id then
      fail(-20200, 'New custodian must differ from the current custodian.');
    end if;

    l_actor_id := of_security_api.current_user_id();
    l_actor_name := of_security_api.current_username();
    update of_asset_assignments
       set returned_at = systimestamp, returned_by_user_id = l_actor_id,
           condition_in_code = l_condition_in,
           notes = substr(
             case when notes is null then '' else notes || chr(10) end ||
             'Transfer: ' || trim(p_reason_text), 1, 2000
           ),
           updated_at = systimestamp, updated_by = l_actor_name
     where id = l_old_assignment_id;

    insert into of_asset_assignments (
      asset_id, assigned_to_user_id, assigned_by_user_id, assigned_at,
      condition_out_code, notes, created_by, updated_by
    ) values (
      l_asset.id, p_new_custodian_user_id, l_actor_id, systimestamp,
      l_condition_out, substr('Transfer: ' || trim(p_reason_text), 1, 2000),
      l_actor_name, l_actor_name
    ) returning id into p_new_assignment_id;

    update of_assets
       set current_location_id = l_location_id,
           row_version = row_version + 1,
           updated_at = systimestamp, updated_by = l_actor_name
     where id = l_asset.id
     returning row_version into p_new_row_version;

    record_event(
      'ASSET_TRANSFERRED', l_asset.id, l_asset.asset_tag,
      'ASSIGNED', 'ASSIGNED', l_asset.current_location_id, l_location_id,
      l_old_custodian, p_new_custodian_user_id, p_reason_text,
      l_asset.row_version, p_new_row_version
    );
  exception
    when no_data_found then
      rollback to of_asset_api_action;
      fail(-20208, 'The active assignment is missing.');
    when others then rollback to of_asset_api_action; raise;
  end transfer_asset;

  procedure return_asset(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_return_location_id     in  number,
    p_condition_in_code      in  varchar2,
    p_notes                  in  varchar2 default null,
    p_new_row_version        out number
  ) is
    l_asset         of_assets%rowtype;
    l_assignment_id number;
    l_custodian     number;
    l_condition     varchar2(30 char);
    l_actor_id      number;
    l_actor_name    varchar2(255 char);
  begin
    savepoint of_asset_api_action;
    p_new_row_version := null;
    lock_asset(p_asset_id, p_expected_row_version, l_asset);
    if l_asset.status_code <> 'ASSIGNED' then
      fail(-20204, 'Return is allowed only while an asset is ASSIGNED.');
    end if;
    assert_location(p_return_location_id);
    l_condition := normalized_condition(p_condition_in_code);
    select id, assigned_to_user_id
      into l_assignment_id, l_custodian
      from of_asset_assignments
     where asset_id = l_asset.id and returned_at is null
       for update;

    l_actor_id := of_security_api.current_user_id();
    l_actor_name := of_security_api.current_username();
    update of_asset_assignments
       set returned_at = systimestamp, returned_by_user_id = l_actor_id,
           condition_in_code = l_condition,
           notes = substr(
             case when notes is null then '' else notes || chr(10) end ||
             trim(p_notes), 1, 2000
           ),
           updated_at = systimestamp, updated_by = l_actor_name
     where id = l_assignment_id;

    update of_assets
       set status_code = 'IN_STOCK', current_location_id = p_return_location_id,
           row_version = row_version + 1,
           updated_at = systimestamp, updated_by = l_actor_name
     where id = l_asset.id
     returning row_version into p_new_row_version;

    record_event(
      'ASSET_RETURNED', l_asset.id, l_asset.asset_tag,
      'ASSIGNED', 'IN_STOCK', l_asset.current_location_id,
      p_return_location_id, l_custodian, null, p_notes,
      l_asset.row_version, p_new_row_version
    );
  exception
    when no_data_found then
      rollback to of_asset_api_action;
      fail(-20208, 'The active assignment is missing.');
    when others then rollback to of_asset_api_action; raise;
  end return_asset;

  procedure open_repair(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_problem_description    in  clob,
    p_provider_name          in  varchar2 default null,
    p_repair_location_id     in  number default null,
    p_condition_in_code      in  varchar2 default null,
    p_repair_id              out number,
    p_new_row_version        out number
  ) is
    l_asset          of_assets%rowtype;
    l_assignment_id  number;
    l_old_custodian  number;
    l_condition      varchar2(30 char);
    l_location_id    number;
    l_actor_id       number;
    l_actor_name     varchar2(255 char);
  begin
    savepoint of_asset_api_action;
    p_repair_id := null;
    p_new_row_version := null;
    assert_clob_text(p_problem_description, 'Problem description');
    lock_asset(p_asset_id, p_expected_row_version, l_asset);
    if l_asset.status_code not in ('IN_STOCK', 'ASSIGNED') then
      fail(-20204, 'Repair may be opened only from IN_STOCK or ASSIGNED.');
    end if;
    l_location_id := coalesce(p_repair_location_id, l_asset.current_location_id);
    assert_location(l_location_id);
    l_actor_id := of_security_api.current_user_id();
    l_actor_name := of_security_api.current_username();
    l_old_custodian := null;

    if l_asset.status_code = 'ASSIGNED' then
      if p_condition_in_code is null then
        fail(-20200, 'Condition in is required when repair closes active custody.');
      end if;
      l_condition := normalized_condition(p_condition_in_code);
      select id, assigned_to_user_id
        into l_assignment_id, l_old_custodian
        from of_asset_assignments
       where asset_id = l_asset.id and returned_at is null
         for update;
      update of_asset_assignments
         set returned_at = systimestamp, returned_by_user_id = l_actor_id,
             condition_in_code = l_condition,
             notes = substr(
               case when notes is null then '' else notes || chr(10) end ||
               'Sent to repair', 1, 2000
             ),
             updated_at = systimestamp, updated_by = l_actor_name
       where id = l_assignment_id;
    elsif p_condition_in_code is not null then
      fail(-20200, 'Condition in applies only when closing active custody.');
    end if;

    insert into of_asset_repairs (
      asset_id, status_code, problem_description, provider_name_snapshot,
      opened_at, row_version, created_by, updated_by
    ) values (
      l_asset.id, 'OPEN', p_problem_description,
      substr(trim(p_provider_name), 1, 200), systimestamp, 1,
      l_actor_name, l_actor_name
    ) returning id into p_repair_id;

    update of_assets
       set status_code = 'IN_REPAIR', current_location_id = l_location_id,
           row_version = row_version + 1,
           updated_at = systimestamp, updated_by = l_actor_name
     where id = l_asset.id
     returning row_version into p_new_row_version;

    record_event(
      'ASSET_REPAIR_OPENED', l_asset.id, l_asset.asset_tag,
      l_asset.status_code, 'IN_REPAIR', l_asset.current_location_id,
      l_location_id, l_old_custodian, null,
      dbms_lob.substr(p_problem_description, 1000, 1),
      l_asset.row_version, p_new_row_version
    );
  exception
    when no_data_found then
      rollback to of_asset_api_action;
      fail(-20208, 'The active assignment is missing.');
    when others then rollback to of_asset_api_action; raise;
  end open_repair;

  procedure close_repair(
    p_asset_id               in  number,
    p_repair_id              in  number,
    p_resolution_description in  clob,
    p_cost_amount            in  number,
    p_currency_code          in  varchar2,
    p_actor_name             in  varchar2,
    p_currency_normalized    out varchar2
  ) is
    l_found number;
  begin
    assert_clob_text(p_resolution_description, 'Resolution description');
    validate_money(p_cost_amount, p_currency_code, p_currency_normalized);
    begin
      select id into l_found
        from of_asset_repairs
       where id = p_repair_id
         and asset_id = p_asset_id
         and status_code in ('OPEN', 'IN_PROGRESS')
         for update;
    exception
      when no_data_found then
        fail(-20209, 'The selected active repair does not match this asset.');
    end;

    update of_asset_repairs
       set status_code = 'COMPLETED',
           resolution_description = p_resolution_description,
           closed_at = systimestamp, cost_amount = p_cost_amount,
           currency_code = p_currency_normalized,
           row_version = row_version + 1,
           updated_at = systimestamp, updated_by = p_actor_name
     where id = p_repair_id;
  end close_repair;

  procedure complete_repair_to_stock(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_repair_id              in  number,
    p_resolution_description in  clob,
    p_stock_location_id      in  number,
    p_cost_amount            in  number default null,
    p_currency_code          in  varchar2 default null,
    p_new_row_version        out number
  ) is
    l_asset        of_assets%rowtype;
    l_actor_name   varchar2(255 char);
    l_currency     varchar2(3 char);
  begin
    savepoint of_asset_api_action;
    p_new_row_version := null;
    lock_asset(p_asset_id, p_expected_row_version, l_asset);
    if l_asset.status_code <> 'IN_REPAIR' then
      fail(-20204, 'Repair completion is allowed only while an asset is IN_REPAIR.');
    end if;
    assert_location(p_stock_location_id);
    l_actor_name := of_security_api.current_username();
    close_repair(
      l_asset.id, p_repair_id, p_resolution_description,
      p_cost_amount, p_currency_code, l_actor_name, l_currency
    );

    update of_assets
       set status_code = 'IN_STOCK', current_location_id = p_stock_location_id,
           row_version = row_version + 1,
           updated_at = systimestamp, updated_by = l_actor_name
     where id = l_asset.id
     returning row_version into p_new_row_version;

    record_event(
      'ASSET_REPAIR_COMPLETED_STOCK', l_asset.id, l_asset.asset_tag,
      'IN_REPAIR', 'IN_STOCK', l_asset.current_location_id,
      p_stock_location_id, null, null,
      dbms_lob.substr(p_resolution_description, 1000, 1),
      l_asset.row_version, p_new_row_version
    );
  exception
    when others then rollback to of_asset_api_action; raise;
  end complete_repair_to_stock;

  procedure complete_repair_to_custodian(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_repair_id              in  number,
    p_resolution_description in  clob,
    p_custodian_user_id      in  number,
    p_condition_out_code     in  varchar2,
    p_to_location_id         in  number,
    p_cost_amount            in  number default null,
    p_currency_code          in  varchar2 default null,
    p_assignment_id          out number,
    p_new_row_version        out number
  ) is
    l_asset        of_assets%rowtype;
    l_actor_id     number;
    l_actor_name   varchar2(255 char);
    l_condition    varchar2(30 char);
    l_currency     varchar2(3 char);
  begin
    savepoint of_asset_api_action;
    p_assignment_id := null;
    p_new_row_version := null;
    lock_asset(p_asset_id, p_expected_row_version, l_asset);
    if l_asset.status_code <> 'IN_REPAIR' then
      fail(-20204, 'Repair completion is allowed only while an asset is IN_REPAIR.');
    end if;
    assert_user(p_custodian_user_id);
    assert_location(p_to_location_id);
    l_condition := normalized_condition(p_condition_out_code);
    l_actor_id := of_security_api.current_user_id();
    l_actor_name := of_security_api.current_username();
    close_repair(
      l_asset.id, p_repair_id, p_resolution_description,
      p_cost_amount, p_currency_code, l_actor_name, l_currency
    );

    insert into of_asset_assignments (
      asset_id, assigned_to_user_id, assigned_by_user_id, assigned_at,
      condition_out_code, notes, created_by, updated_by
    ) values (
      l_asset.id, p_custodian_user_id, l_actor_id, systimestamp,
      l_condition, 'Returned from repair', l_actor_name, l_actor_name
    ) returning id into p_assignment_id;

    update of_assets
       set status_code = 'ASSIGNED', current_location_id = p_to_location_id,
           row_version = row_version + 1,
           updated_at = systimestamp, updated_by = l_actor_name
     where id = l_asset.id
     returning row_version into p_new_row_version;

    record_event(
      'ASSET_REPAIR_COMPLETED_CUSTODY', l_asset.id, l_asset.asset_tag,
      'IN_REPAIR', 'ASSIGNED', l_asset.current_location_id,
      p_to_location_id, null, p_custodian_user_id,
      dbms_lob.substr(p_resolution_description, 1000, 1),
      l_asset.row_version, p_new_row_version
    );
  exception
    when others then rollback to of_asset_api_action; raise;
  end complete_repair_to_custodian;

  procedure mark_lost(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_reason_text            in  varchar2,
    p_new_row_version        out number
  ) is
    l_asset       of_assets%rowtype;
    l_actor_id    number;
    l_actor_name  varchar2(255 char);
    l_related_user number;
  begin
    savepoint of_asset_api_action;
    p_new_row_version := null;
    assert_text(p_reason_text, 'Loss reason', 1000);
    lock_asset(p_asset_id, p_expected_row_version, l_asset);
    if l_asset.status_code in ('RETIRED', 'LOST') then
      fail(-20204, 'A retired or lost asset is terminal.');
    end if;
    l_actor_id := of_security_api.current_user_id();
    l_actor_name := of_security_api.current_username();
    l_related_user := null;

    if l_asset.status_code = 'RESERVED' then
      select reserved_for_user_id into l_related_user
        from of_asset_reservations
       where asset_id = l_asset.id and status_code = 'ACTIVE'
         for update;
      update of_asset_reservations
         set status_code = 'RELEASED', released_at = systimestamp,
             released_by_user_id = l_actor_id,
             reason_text = substr('Asset lost: ' || trim(p_reason_text), 1, 1000),
             updated_at = systimestamp, updated_by = l_actor_name
       where asset_id = l_asset.id and status_code = 'ACTIVE';
    elsif l_asset.status_code = 'ASSIGNED' then
      select assigned_to_user_id into l_related_user
        from of_asset_assignments
       where asset_id = l_asset.id and returned_at is null
         for update;
      update of_asset_assignments
         set returned_at = systimestamp, returned_by_user_id = l_actor_id,
             condition_in_code = 'LOST',
             notes = substr(
               case when notes is null then '' else notes || chr(10) end ||
               'Lost: ' || trim(p_reason_text), 1, 2000
             ),
             updated_at = systimestamp, updated_by = l_actor_name
       where asset_id = l_asset.id and returned_at is null;
    elsif l_asset.status_code = 'IN_REPAIR' then
      update of_asset_repairs
         set status_code = 'CANCELLED', closed_at = systimestamp,
             resolution_description = to_clob(
               'Cancelled because asset was marked lost: ' || trim(p_reason_text)
             ),
             row_version = row_version + 1,
             updated_at = systimestamp, updated_by = l_actor_name
       where asset_id = l_asset.id
         and status_code in ('OPEN', 'IN_PROGRESS');
    end if;

    update of_assets
       set status_code = 'LOST', row_version = row_version + 1,
           updated_at = systimestamp, updated_by = l_actor_name
     where id = l_asset.id
     returning row_version into p_new_row_version;

    record_event(
      'ASSET_MARKED_LOST', l_asset.id, l_asset.asset_tag,
      l_asset.status_code, 'LOST', l_asset.current_location_id,
      l_asset.current_location_id, l_related_user, null, p_reason_text,
      l_asset.row_version, p_new_row_version
    );
  exception
    when no_data_found then
      rollback to of_asset_api_action;
      fail(-20208, 'The active lifecycle relationship is missing.');
    when others then rollback to of_asset_api_action; raise;
  end mark_lost;

  procedure retire_asset(
    p_asset_id               in  number,
    p_expected_row_version   in  number,
    p_reason_text            in  varchar2,
    p_new_row_version        out number
  ) is
    l_asset      of_assets%rowtype;
    l_actor_name varchar2(255 char);
  begin
    savepoint of_asset_api_action;
    p_new_row_version := null;
    assert_text(p_reason_text, 'Retirement reason', 1000);
    lock_asset(p_asset_id, p_expected_row_version, l_asset);
    if l_asset.status_code not in ('IN_STOCK', 'IN_REPAIR') then
      fail(-20204, 'Retirement is allowed only from IN_STOCK or IN_REPAIR.');
    end if;
    l_actor_name := of_security_api.current_username();

    if l_asset.status_code = 'IN_REPAIR' then
      update of_asset_repairs
         set status_code = 'CANCELLED', closed_at = systimestamp,
             resolution_description = to_clob(
               'Cancelled by retirement: ' || trim(p_reason_text)
             ),
             row_version = row_version + 1,
             updated_at = systimestamp, updated_by = l_actor_name
       where asset_id = l_asset.id
         and status_code in ('OPEN', 'IN_PROGRESS');
    end if;

    update of_assets
       set status_code = 'RETIRED', row_version = row_version + 1,
           updated_at = systimestamp, updated_by = l_actor_name
     where id = l_asset.id
     returning row_version into p_new_row_version;

    record_event(
      'ASSET_RETIRED', l_asset.id, l_asset.asset_tag,
      l_asset.status_code, 'RETIRED', l_asset.current_location_id,
      l_asset.current_location_id, null, null, p_reason_text,
      l_asset.row_version, p_new_row_version
    );
  exception
    when others then rollback to of_asset_api_action; raise;
  end retire_asset;
end of_asset_api;
/

--------------------------------------------------------------------------------
-- 04. Immutable asset status history
--------------------------------------------------------------------------------

create or replace trigger of_asset_history_guard_trg
  before update or delete on of_asset_status_history
  for each row
begin
  raise_application_error(
    -20220,
    'Asset status history is immutable; update and delete are not allowed.'
  );
end;
/

--------------------------------------------------------------------------------
-- 05. Installation inventory
-- Expected: 9 rows, all VALID.
--------------------------------------------------------------------------------

select object_name, object_type, status
  from user_objects
 where object_name in (
   'OF_ASSET_TYPES', 'OF_ASSETS', 'OF_ASSET_RESERVATIONS',
   'OF_ASSET_ASSIGNMENTS', 'OF_ASSET_REPAIRS',
   'OF_ASSET_STATUS_HISTORY', 'OF_ASSET_API',
   'OF_ASSET_HISTORY_GUARD_TRG'
 )
   and object_type in ('TABLE', 'PACKAGE', 'PACKAGE BODY', 'TRIGGER')
 order by object_type, object_name;

--------------------------------------------------------------------------------
-- 06. Seed inventory
-- Expected: 6 rows.
--------------------------------------------------------------------------------

select code, name, requires_serial_no, default_warranty_months, is_active
  from of_asset_types
 where code in (
   'LAPTOP', 'DESKTOP', 'MONITOR', 'MOBILE_PHONE', 'PRINTER', 'FURNITURE'
 )
 order by code;

--------------------------------------------------------------------------------
-- End P06 installer. Expected SQL Scripts statements: 7.
--------------------------------------------------------------------------------
